name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- master

stages:
- stage: Install_Terraform
  displayName: Install Terraform 0.11.14 on build agent and add to $PATH
  jobs:
  - job: Installing_Terraform
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - task: Bash@3  
      inputs:
        filePath: './scripts/install_terraform.sh'
    - script: terraform --version 
  - job: Validate_Terrafrom_FMT
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: terraform fmt -check  
      