trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: sudo apt-get install unzip
- script: wget https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip
- script: unzip terraform_0.11.14_linux_amd64.zip
- script: sudo mv terraform /usr/local/bin/
- script: terraform --version 